### ISSUE TITLE
mem::forget(completion) unsafety? 

### ISSUE THREAD

**Issue by goffrie** [spacejam/rio#11] opened 2020-02-07 10:19 UTC
It seems to me that the soundness of Completion relies on the fact that it waits for the operation to complete in its Drop impl. But per the leakpocalypse it's safe to just forget the completion, side-stepping that?

**Comment by twissel** [comment] 2020-02-07 22:06
Similar  issue was also  discussed in https://github.com/spacejam/rio/issues/1

**Comment by spacejam** [comment] 2020-02-08 17:47
Yeah. Personally, I consider `mem::forget` to be an incorrectly safe operation for this reason. I think this needs to be better documented.

**Comment by DemiMarie-parity** [comment] 2020-02-19 20:05
This can be avoided by returning `Pin<Box<Completion>>` and `impl !Unpin for Completion`.  There should be other ways to do this as well, such as requiring a `Pin<&mut Completion>` argument in various places.

**Comment by goffrie** [comment] 2020-02-19 20:07
Can't you still mem::forget the box?

**Comment by DemiMarie-parity** [comment] 2020-02-21 13:20
You can :(.  The only solution I can think of is for `rio` to own all buffers. That will be needed anyway for preregistration, though, so it isn’t all bad.

**Comment by spacejam** [comment] 2020-02-21 18:42
My personal feeling is that `mem::forget` is unlikely to be used on `Completion`. It's a dangerous tool in general that I believe most people rarely rely on. Can you folks think of a realistic reason someone may try to use it on this? I know this is not necessarily a water-tight argument, but personally I'm not sure we should significantly reduce the usability of an API due to an issue that you can only encounter if you do something kind of foolish to begin with. Are there cases where it doesn't seem foolish to use `mem::forget` over `drop`?

**Comment by twissel** [comment] 2020-02-21 23:42
For me mem::forget  it's not the issue, but for example read or timeout is the issue, why do i need to wait until read is finished  (drop  called)?,  passing ownership to kernel is the only way i think.

**Comment by Shnatsel** [comment] 2020-04-28 14:41
`mem::forget()` is a rather contrived example, but it's marked safe because you can get identical behavior by creating a reference cycle using `Rc` or `Arc` in safe code, and that cannot be fixed without introducing a garbage collector. And a leak caused by a reference cycle is a much more realistic scenario, especially seeing how prevalent `Arc` is in async code.

**Comment by stjepang** [comment] 2020-04-28 14:58
I like rio's API a lot! While it is technically unsound because it can cause undefined behavior in safe code, I don't think it needs a lot of changes to be sound.

All we need to do is require the user to open *one* line of unsafe code and to declare "I know what I'm doing". Rio's constructor could be made unsafe, or some kind of getter method on `Rio` that gives you its convenient API.

That way we get *technical* soundness and keep the convenience. Anyways... I'm thinking this is a lot of talk for what is a trivially easy problem to solve (:

**Comment by DemiMarie-parity** [comment] 2020-04-28 21:47
@stjepang why is it bad for rio to own the buffers?  That allows for preregistration (a large performance improvement).

**Comment by Shnatsel** [comment] 2020-05-06 13:02
withoutboats has published a blog post on io-uring and safe Rust wrappers for it. It discusses the issues with API reliant on Drop running beyond the obvious safety issues and proposes some possible solutions. https://boats.gitlab.io/blog/post/io-uring/

**Comment by spacejam** [comment] 2020-05-11 11:37
boats considers mem::forget to be a bigger issue than I do. mem::forget is unsafe in real code, the same as a memory leak is unsafe in real code. I don't view the unsoundness of this library to be meaningful in real systems. I view Rust's design decisions as unfortunate to allow such bypasses of the borrow checker to become possible with leaks, but ultimately one that does not actually mean anything for people building real systems that need to guarantee that they do not contain leaks using [LSAN](https://github.com/spacejam/sled/blob/df81d300c6f3cc8c1ba29ca81d0cf9620641e460/scripts/sanitizers.sh) anyway etc...

**Closed by spacejam** 2020-05-11 11:37 UTC
